(function(){
'use strict';
var form=document.getElementById('adultForm'),key='adultEmergencyFormEnglish';
var painLabels=['0 / No pain','2 / Mild','4 / Moderate','6 / Severe','8 / Very severe','10 / Worst pain'];
document.getElementById('birthDate').max=new Date().toISOString().slice(0,10);
function radio(name){var e=form.querySelector('input[name="'+name+'"]:checked');return e?e.value:'';}
function values(name){return Array.from(form.querySelectorAll('input[name="'+name+'"]:checked')).map(function(e){return e.value;}).join(', ');}
function value(id){var e=document.getElementById(id);return e&&!e.disabled?e.value:'';}
function age(){var s=value('birthDate');if(!s)return'';var p=s.split('-').map(Number),b=new Date(p[0],p[1]-1,p[2]),n=new Date(),a=n.getFullYear()-b.getFullYear();if(n.getMonth()<b.getMonth()||(n.getMonth()===b.getMonth()&&n.getDate()<b.getDate()))a--;return a>=0?a+' years':'';}
function branch(){var c=radio('complaint');document.getElementById('injurySection').hidden=c!=='Injury / pain';document.getElementById('illnessSection').hidden=c!=='Fever / illness';document.querySelectorAll('#injurySection input,#injurySection select,#illnessSection input,#illnessSection select').forEach(function(e){e.disabled=e.closest('section').hidden;});}
function pain(){document.getElementById('painOutput').textContent=painLabels[Number(document.getElementById('pain').value)];}
function snapshot(){var d={};new FormData(form).forEach(function(v,k){if(d[k])d[k]=[].concat(d[k],v);else d[k]=v;});d.pain=value('pain');return d;}
function save(){try{sessionStorage.setItem(key,JSON.stringify(snapshot()));}catch(e){}}
function restore(){var d;try{d=JSON.parse(sessionStorage.getItem(key)||'null');}catch(e){d=null;}if(!d)return;Object.keys(d).forEach(function(n){var vs=[].concat(d[n]);form.querySelectorAll('[name="'+CSS.escape(n)+'"]').forEach(function(e){if(e.type==='radio'||e.type==='checkbox')e.checked=vs.indexOf(e.value)!==-1;else e.value=vs[0];});});}
function text(){var e=[['','【Emergency questionnaire / English】'],['Name',value('patientName')],['Katakana',value('patientKana')],['DOB',value('birthDate')+(age()?' '+age():'')],['Sex',value('sex')],['Patient ID',value('patientId')],['Visit',value('visitStatus')],['Completed by',value('completedBy')],['Arrival',value('visitReason')],['Referral',value('referralSource')],['Chief complaint',radio('complaint')],['Onset',value('onset')],['Temperature',value('temperature')?value('temperature')+' C':''],['Course',value('mainSymptoms')]];if(radio('complaint')==='Injury / pain')e.push(['Injury symptoms',values('injurySymptoms')],['Site',value('injurySite')],['Cause',value('injuryCause')],['Operations',value('surgeryHistory')]);if(radio('complaint')==='Fever / illness')e.push(['Illness symptoms',values('illnessSymptoms')],['Similar cases',value('similarSymptoms')],['Travel',value('travel')]);e.push(['Conditions',[values('conditions'),value('otherCondition')].filter(Boolean).join(', ')],['Medications',value('medications')],['Allergies',value('allergies')],['Last intake',value('lastMeal')],['Weight',value('weight')?value('weight')+'kg':''],['Pregnancy',[value('pregnancy'),value('pregnancyDetail')].filter(Boolean).join(' ')],['Pain',painLabels[Number(value('pain'))]],['Notes',value('notes')]);return window.PediatricQR.buildPipeText(e);}
form.addEventListener('input',function(){branch();pain();save();});form.addEventListener('change',function(){branch();pain();save();});
form.addEventListener('submit',function(ev){ev.preventDefault();var err=document.getElementById('formError');if(!form.reportValidity()){err.textContent='Please complete all required fields.';err.hidden=false;return;}try{var t=text();window.PediatricQR.render(document.getElementById('qrcode'),t);document.getElementById('qrText').textContent=t;document.getElementById('qrResult').hidden=false;err.hidden=true;save();document.getElementById('qrResult').scrollIntoView({behavior:'smooth',block:'start'});}catch(ex){err.textContent=ex.message;err.hidden=false;}});
document.getElementById('resetButton').addEventListener('click',function(){if(!confirm('Clear all answers?'))return;sessionStorage.clear();form.reset();document.getElementById('qrResult').hidden=true;document.getElementById('qrcode').replaceChildren();document.getElementById('formError').hidden=true;branch();pain();scrollTo({top:0,behavior:'smooth'});});
restore();branch();pain();
})();
